version: '3.3'
services:
  back:
    build: 
      context: ./src
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    ports:
      - 8000:8000
    depends_on: 
      - db
      - elasticsearch
    networks:
      - redis
  db:
    image: postgres:12.0-alpine
    env_file:
      - ./.env
    ports:
      - 5432:5432
    volumes:
      - ./pg-data:/var/lib/postgresql/data/
      - ./src/create_schema.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always
    networks:
      - redis
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.7.0
    container_name: elasticsearch
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
    user: "1000"
    volumes:
      - ./.es-data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - redis
  kibana:
    image: docker.elastic.co/kibana/kibana:7.10.1
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    env_file:
      - ./.env
    networks:
      - redis

  executable:
    container_name: etl_executable_back
    build:
      context: .
      dockerfile: etl/Dockerfile
    env_file:
      - ./.env
    environment:
        - REDIS_HOST=redis
        - RUN_ONCE=0
    restart: always
    tty: true
    volumes:
      - ./etl/__init__.py:/etl.py
    command: sleep infinity
    depends_on:
      - db
      - elasticsearch
    networks:
      - redis

  pgadmin:
    container_name: pgadmin-back
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: 'pgadmin4@pgadmin.org'
      PGADMIN_DEFAULT_PASSWORD: 'admin'

    ports:
      - "${PGADMIN_PORT:-5050}:80"
    restart: unless-stopped
    depends_on:
      - db
    networks:
      - redis


networks:
  redis:
    external:
      name: redis